apiVersion: v1
kind: Namespace
metadata:
  name: upstream-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: upstream-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /intentionally-broken
              port: 80
            periodSeconds: 3
            failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: upstream-lab
spec:
  selector:
    app: demo-api
  ports:
    - port: 80
      targetPort: 80
