/** Auto-generated by scripts/generate-static-blog-registry.mjs — do not edit manually */
export const STATIC_BLOG_SLUGS = new Set(["monitor-docling-using-alertmend","monitor-langfuse-using-alertmend","monitor-milvus-using-alertmend"])

export function isStaticBlog(slug: string): boolean {
  return STATIC_BLOG_SLUGS.has(slug)
}

/** URL path for any blog post (static HTML or React markdown). */
export function getBlogPostPath(slug: string): string {
  return '/blog/' + slug
}
