/** Auto-generated by scripts/generate-static-blog-registry.mjs — do not edit manually */
export const STATIC_BLOG_SLUGS = new Set(["503-no-healthy-upstream","kubernetes-crashloopbackoff-fix","kubernetes-imagepullbackoff-fix","make-error-127","monitor-docling-using-alertmend","monitor-langfuse-using-alertmend","monitor-litellm-using-alertmend","monitor-milvus-using-alertmend","monitor-ollama-using-alertmend","monitor-open-webui-using-alertmend","monitor-vllm-using-alertmend","openclaw-cloud-infra-slack-telegram","url-monitoring-automated-fixes","vibe-coded-app-vm-observability"])

export function isStaticBlog(slug: string): boolean {
  return STATIC_BLOG_SLUGS.has(slug)
}

/** URL path for any blog post (static HTML or React markdown). */
export function getBlogPostPath(slug: string): string {
  return '/blog/' + slug
}
