/** Auto-generated by scripts/generate-static-blog-registry.mjs — do not edit manually */
export const STATIC_BLOG_SLUGS = new Set(["503-no-healthy-upstream","ai-agent-observability-in-production","best-1-click-logging-and-metrics-tools","best-ai-agent-observability-tools","elasticsearch-caching-issues","elasticsearch-disk-out-of-space-incident","elasticsearch-shard-relocation-incidents-on-kubernetes","enterprise-ai-agent-observability","exit-code-5","gpu-reliability-for-llm-workloads","keep-ai-agents-online","kubernetes-crashloopbackoff-fix","kubernetes-imagepullbackoff-fix","make-error-127","monitor-docling-using-alertmend","monitor-langfuse-using-alertmend","monitor-langgraph-agents-in-production","monitor-litellm-using-alertmend","monitor-milvus-using-alertmend","monitor-ollama-using-alertmend","monitor-open-webui-using-alertmend","monitor-vllm-using-alertmend","monitoring-mcp-servers-in-production","multi-agent-system-reliability","openclaw-cloud-infra-slack-telegram","optimizing-high-jvm-heap-usage-in-elasticsearch","reduce-mttr-for-ai-agents","self-healing-ai-agents","top-kubernetes-cost-management-solutions","url-monitoring-automated-fixes","vibe-coded-app-vm-observability"])

export function isStaticBlog(slug: string): boolean {
  return STATIC_BLOG_SLUGS.has(slug)
}

/** URL path for any blog post (static HTML or React markdown). */
export function getBlogPostPath(slug: string): string {
  return '/blog/' + slug
}
