// Node ESM loader hook that intercepts .css and .module.css imports during
// the prerender step so tsx can run the React tree without a CSS bundler.
//
// CSS-module class names are returned via a Proxy, but — critically — the
// names it yields are generated by the SAME deterministic function that
// `vite build` uses (scripts/css-module-name.mjs). That makes the prerendered
// HTML's class names byte-identical to the compiled stylesheet's selectors, so
// the static (pre-hydration) page is fully styled.
//
// The old behaviour returned the raw local name (styles.header === 'header'),
// which matched nothing in Vite's hashed stylesheet until the JS bundle
// hydrated — a flash of unstyled content on every cold load.
import { fileURLToPath } from 'node:url';

// Absolute URL of the shared name generator, embedded into the generated
// virtual module so it can resolve `scopedName` at runtime.
const nameHelperUrl = new URL('./css-module-name.mjs', import.meta.url).href;

export async function resolve(specifier, context, nextResolve) {
  if (specifier.endsWith('.css')) {
    // Resolve to the real file path so we can derive a stable scoped name.
    let filename = specifier;
    try {
      const resolved = await nextResolve(specifier, context);
      if (resolved?.url?.startsWith('file:')) {
        filename = fileURLToPath(resolved.url);
      }
    } catch {
      // Fall back to the raw specifier; basename is still usable.
    }
    return {
      shortCircuit: true,
      // encodeURIComponent escapes commas, so the data-URL separator is safe.
      url: `data:text/css;file=${encodeURIComponent(filename)},`,
      format: 'module',
    };
  }
  return nextResolve(specifier, context);
}

export async function load(url, context, nextLoad) {
  if (url.startsWith('data:text/css')) {
    const match = url.match(/file=([^,]*)/);
    const filename = match ? decodeURIComponent(match[1]) : '';
    const source = `
import { scopedName } from ${JSON.stringify(nameHelperUrl)};
const file = ${JSON.stringify(filename)};
const proxy = new Proxy({}, {
  get(_, prop) {
    if (prop === '__esModule') return true;
    if (prop === 'default') return proxy;
    if (typeof prop === 'string') return scopedName(prop, file);
    return undefined;
  },
});
export default proxy;
`;
    return { format: 'module', shortCircuit: true, source };
  }
  return nextLoad(url, context);
}
